#pragma once

#include <cstddef>
#include <cstdint>

namespace flm::phi4 {

enum class ContinuationRoute {
    Append,
    Reprefill
};

enum class ForcedContinuationRoute {
    Automatic,
    Append,
    Reprefill
};

// BEGIN generated by tools/calibrate_phi4_corelib_continuation.py
//
// Generated. Do not edit this block by hand; re-run the calibrator.
//
// Design Section 10.7: the largest sampled suffix length whose append
// p95 is lower than re-prefill p95 at BOTH history lengths [512, 2048],
// after asserting the winning lengths are a prefix of the sampled set.
//
// verdict:  selected
// winners:  [1, 2, 4] of sampled [1, 2, 4, 8, 12, 16, 24, 32, 64, 128, 256]
// measured: 2026-09-02T16:32:18Z on xcomedusad-43
// corelib:  a523b23837c9bea3b06f8f8ae74e1e8292092eb73aaa93791022c448b865ecdb
// model:    d6f503a9ea142c8b6320313d6ae341a88049b1b8ef01e641b2313fe42cdc7309
inline constexpr std::uint32_t kContinuationAppendThreshold = 4;
// END generated by tools/calibrate_phi4_corelib_continuation.py

inline constexpr ContinuationRoute SelectContinuationRoute(
    std::size_t suffix_tokens,
    ForcedContinuationRoute forced) noexcept {
    if (suffix_tokens == 0) {
        return ContinuationRoute::Reprefill;
    }
    switch (forced) {
        case ForcedContinuationRoute::Append:
            return ContinuationRoute::Append;
        case ForcedContinuationRoute::Reprefill:
            return ContinuationRoute::Reprefill;
        case ForcedContinuationRoute::Automatic:
            return suffix_tokens <= kContinuationAppendThreshold
                       ? ContinuationRoute::Append
                       : ContinuationRoute::Reprefill;
    }
    return ContinuationRoute::Reprefill;
}

inline constexpr const char* ContinuationRouteName(
    ContinuationRoute route) noexcept {
    return route == ContinuationRoute::Append
               ? "append"
               : "reprefill";
}

}  // namespace flm::phi4
