set(FLM_CORELIB_AIE4_SOURCES
    "${CMAKE_CURRENT_LIST_DIR}/corelib_api.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/corelib_fatal_record.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/corelib_runtime.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/phi4_corelib_aie4.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/phi4_corelib_host.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/phi4_corelib_manifest.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/phi4_corelib_weights.cpp"
    "${CMAKE_CURRENT_LIST_DIR}/phi4_corelib_shape_plan.cpp")
