"""Select the release-fixed Phi-4 continuation append threshold. Task 14.

Design Section 10.7 fixes ONE integer, `kContinuationAppendThreshold`, applied
regardless of history length:

    append when `suffix_tokens <= continuation_append_threshold`; and
    clear plus fresh re-prefill when the suffix is larger.

and it fixes how that integer is chosen:

    the largest suffix length whose append p95 is lower at both history
    lengths, but only after asserting that the set of winning sampled lengths
    is a prefix-contiguous set. If the winners are non-monotonic or none wins,
    the threshold is zero and every prefix hit re-prefills.

This script implements exactly that sentence against the committed Task 13
measurement. Three things about it are worth stating up front, because each is
a place where an obvious implementation would be wrong.

**The conjunction is over histories, and it is not a worst-case reduction.**
"Append p95 is lower at both history lengths" means `append[h] < reprefill[h]`
for every `h`. Collapsing the histories first -- comparing the largest append
p95 against the smallest re-prefill p95 -- is strictly stronger and would
reject suffixes that genuinely win at both.

**The suffix grid is a floor, not a whitelist.** Section 10.7 names suffix
lengths 1, 2, 32, 128 and 256. Task 13 measured that grid and reported the
threshold 2; that answer was retracted, because on `{1, 2, 32, ...}` the last
winning sampled length is 2 whether the true crossover is at 3 or at 31. The
denser 11-point grid Task 13 went on to measure resolves it. So the five named
lengths are REQUIRED to be present and every additional measured length is
USED. Dropping the extra points would faithfully reproduce a retracted answer.
The two history lengths are treated the other way round -- required and
exclusive -- because the conjunction ranges over them, so adding a third would
silently change the rule rather than sharpen it.

**A non-interleaved record is refused outright.** In a non-interleaved run the
two routes are measured in separate blocks, so a machine regime shift lands on
one route and not the other. On the shared lab box that is not hypothetical:
Task 13 measured a 1.8x swing in decode throughput between runs of the same
binary within two hours. The first round of the crossover sweep was
non-interleaved and its answer was retracted. Refusing is not the same as
selecting zero: zero is a measured outcome, and a record that cannot support
any outcome is an input error.

What this script does NOT do, deliberately: it does not emit a per-history
table, a cost model, or anything the runtime consults. Section 10.7 makes the
threshold a release-fixed backend constant, not model-package data and not a
runtime calibration, so the only artefact is one integer in a header.

Usage::

    python -m tools.calibrate_phi4_corelib_continuation \\
        --baseline docs/docs/benchmarks/phi4_aie4_baseline.json \\
        --crossover-history docs/docs/benchmarks/phi4_aie4_crossover_history.json \\
        --header src/include/models/phi4/phi4_corelib_aie4_tuning.hpp \\
        --document docs/docs/benchmarks/phi4_results.md [--check]
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import math
import pathlib
import re
import sys
from typing import Iterable, Mapping, Sequence

# Section 10.7 pins both history lengths. The winner rule is a conjunction over
# this set, so it is required AND exclusive: see the module docstring.
REQUIRED_HISTORIES = (512, 2048)

# Section 10.7 pins these suffix lengths as the measurement grid. They are a
# floor: any additional measured length is used. See the module docstring for
# why -- the five-point grid produced the retracted answer "2".
REQUIRED_SUFFIXES = (1, 2, 32, 128, 256)

MIN_WARM_SAMPLES = 5

ROUTES = ("append", "reprefill")

_HEADER_BEGIN = "// BEGIN generated by tools/calibrate_phi4_corelib_continuation.py"
_HEADER_END = "// END generated by tools/calibrate_phi4_corelib_continuation.py"
_HEADER_DECL = re.compile(
    r"^[ \t]*inline constexpr std::uint32_t kContinuationAppendThreshold"
    r"[ \t]*=[ \t]*\d+[ \t]*;[ \t]*$",
    re.MULTILINE,
)

_DOCUMENT_BEGIN = "<!-- BEGIN phi4-continuation-threshold -->"
_DOCUMENT_END = "<!-- END phi4-continuation-threshold -->"


class CalibrationError(Exception):
    """A record, header or document this script refuses to act on."""


# --------------------------------------------------------------------------
# Statistics
# --------------------------------------------------------------------------


def percentile_ns(samples: Iterable[float], quantile: float) -> float:
    """Nearest-rank percentile.

    Nearest-rank rather than an interpolating definition because that is what
    the Task 13 recorder used, and this script cross-checks every recorded
    p50/p95 against a recomputation from the raw samples. A different
    definition here would turn that cross-check into noise.
    """
    ordered = sorted(samples)
    if not ordered:
        raise CalibrationError("cannot take a percentile of zero samples")
    if not 0.0 < quantile <= 1.0:
        raise CalibrationError(f"quantile {quantile!r} is outside (0, 1]")
    rank = math.ceil(quantile * len(ordered))
    return ordered[min(len(ordered) - 1, max(0, rank - 1))]


# --------------------------------------------------------------------------
# The Section 10.7 selection rule
# --------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class Selection:
    threshold: int
    verdict: str
    winners: tuple
    ordered: tuple
    diagnostics: tuple


def _is_int(value) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def _number(entry: Mapping, key: str, where: str) -> float:
    if key not in entry:
        raise CalibrationError(f"{where}: missing {key!r}")
    value = entry[key]
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise CalibrationError(f"{where}: {key!r} is not a number: {value!r}")
    return float(value)


def _entry_wins(suffix, entry: Mapping) -> bool:
    """Does append beat re-prefill at EVERY history recorded for `suffix`?

    Two entry shapes are accepted and they must not be mixed:

      * `{"append_p95": x, "reprefill_p95": y}` -- one history; and
      * `{"per_history": {h: {"append_p95": x, "reprefill_p95": y}, ...}}`.

    The comparison is strict. Section 10.7 says append p95 must be LOWER, so a
    tie is not a win and routes to re-prefill.
    """
    where = f"suffix {suffix}"
    if not isinstance(entry, Mapping):
        raise CalibrationError(f"{where}: sample entry is not a mapping")
    flat = "append_p95" in entry or "reprefill_p95" in entry
    nested = "per_history" in entry
    if flat and nested:
        raise CalibrationError(
            f"{where}: entry mixes the flat and per-history shapes; pick one"
        )
    if not flat and not nested:
        raise CalibrationError(
            f"{where}: entry has neither 'append_p95'/'reprefill_p95' nor "
            f"'per_history'"
        )
    if flat:
        return _number(entry, "append_p95", where) < _number(
            entry, "reprefill_p95", where
        )

    per_history = entry["per_history"]
    if not isinstance(per_history, Mapping) or not per_history:
        raise CalibrationError(f"{where}: 'per_history' is empty")
    return all(
        _number(measured, "append_p95", f"{where} history {history}")
        < _number(measured, "reprefill_p95", f"{where} history {history}")
        for history, measured in sorted(per_history.items())
    )


def select_threshold_detailed(samples: Mapping) -> Selection:
    """Apply the Section 10.7 rule and say which branch it took.

    Verdicts: `empty`, `no_winner`, `non_monotonic`, `selected`. The first
    three all yield threshold zero -- every prefix hit re-prefills -- and only
    `non_monotonic` is a signal that something is wrong. With an unstable
    upper bracket edge, a non-prefix winner set says the machine moved during
    the sweep, not that append got faster at a longer suffix than a shorter
    one.
    """
    for suffix in samples:
        if not _is_int(suffix):
            raise CalibrationError(f"suffix length {suffix!r} is not an integer")
        if suffix <= 0:
            raise CalibrationError(f"suffix length {suffix!r} is not positive")

    ordered = tuple(sorted(samples))
    if not ordered:
        return Selection(
            0,
            "empty",
            (),
            (),
            ("no sampled suffix lengths; every prefix hit re-prefills",),
        )

    winners = tuple(suffix for suffix in ordered if _entry_wins(suffix, samples[suffix]))
    if not winners:
        return Selection(
            0,
            "no_winner",
            (),
            ordered,
            (
                "append p95 beat re-prefill p95 at no sampled suffix length; "
                "every prefix hit re-prefills",
            ),
        )

    prefix = ordered[: len(winners)]
    if winners != prefix:
        losses = [suffix for suffix in prefix if suffix not in winners]
        late = [suffix for suffix in winners if suffix not in prefix]
        return Selection(
            0,
            "non_monotonic",
            winners,
            ordered,
            (
                "the winning suffix lengths are not a prefix of the sampled "
                f"set: append lost at {losses} and then won again at {late}. "
                "Append cost grows with suffix length, so this is the machine "
                "moving during the sweep, not a real re-crossing. Threshold "
                "is zero and every prefix hit re-prefills.",
            ),
        )

    return Selection(int(max(winners)), "selected", winners, ordered, ())


def select_threshold(samples: Mapping) -> int:
    """The Section 10.7 rule, as one integer."""
    return select_threshold_detailed(samples).threshold


# --------------------------------------------------------------------------
# Ingestion
# --------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class RoutePoint:
    history_rows: int
    suffix: int
    route: str
    count: int
    p50_ns: float
    p95_ns: float


@dataclasses.dataclass(frozen=True)
class Measurements:
    histories: tuple
    suffixes: tuple
    points: Mapping
    identity: Mapping
    recorded_crossover: Mapping
    decision_rule: str

    def point(self, history: int, suffix: int, route: str) -> RoutePoint:
        return self.points[(history, suffix)][route]

    def samples(self) -> dict:
        """The `select_threshold` input, in the per-history shape."""
        return {
            suffix: {
                "per_history": {
                    history: {
                        "append_p95": self.point(history, suffix, "append").p95_ns,
                        "reprefill_p95": self.point(
                            history, suffix, "reprefill"
                        ).p95_ns,
                    }
                    for history in self.histories
                }
            }
            for suffix in self.suffixes
        }

    def winners_by_history(self) -> dict:
        """Per history, the suffix lengths at which append p95 wins."""
        return {
            history: tuple(
                suffix
                for suffix in self.suffixes
                if self.point(history, suffix, "append").p95_ns
                < self.point(history, suffix, "reprefill").p95_ns
            )
            for history in self.histories
        }

    def unclosed_histories(self) -> tuple:
        """Histories whose own winner set is NOT downward-closed.

        Section 10.7 asserts monotonicity of the CONJUNCTION, and that is the
        gate. This is the same property one level down, per history, and it is
        worth checking for two reasons.

        It carries the same meaning: append cost grows with suffix length, so a
        loss at a short suffix followed by a win at a longer one at the SAME
        history is the machine moving during the sweep.

        And it is the exact condition under which `min` over per-history
        ceilings stops equalling the Section 10.7 answer -- the identity the
        cross-run bound in `history_agreement` would need in order to be an
        equality rather than an upper bound. Here the winner sets are known, so
        unlike in a stored crossover record the property can actually be
        checked.
        """
        found = []
        for history, won in self.winners_by_history().items():
            if won != self.suffixes[: len(won)]:
                missing = [s for s in self.suffixes[: len(won)] if s not in won]
                found.append(
                    f"history {history}: append lost at {missing} and won again "
                    f"at a longer suffix; winners {list(won)} are not a prefix "
                    f"of the sampled set {list(self.suffixes)}"
                )
        return tuple(found)

    def crossover_disagreements(self, selection: Selection) -> tuple:
        """Compare the p95 rule against the recorder's own p50-based verdict.

        Task 13's `append_wins_up_to` was decided by a different statistic -- a
        p50 gap that had to clear both the within-point spread and the drift
        across the point. Section 10.7's rule is p95. They should agree; where
        they do not, the constant rests on a statistic the published bracket
        contradicts, and that has to be said rather than resolved silently.
        """
        if not self.recorded_crossover:
            return ()
        found = []
        winners = self.winners_by_history()
        for history in self.histories:
            recorded = self.recorded_crossover.get(str(history))
            if not isinstance(recorded, Mapping):
                continue
            if "append_wins_up_to" not in recorded:
                continue
            declared = recorded["append_wins_up_to"]
            ours = max(winners[history]) if winners[history] else 0
            if declared is None:
                declared = 0
            if declared != ours:
                found.append(
                    f"history {history}: the recorded bracket says append wins "
                    f"up to {declared}, the Section 10.7 p95 rule says {ours}"
                )
        return tuple(found)


def _require_point_fields(raw, index: int) -> RoutePoint:
    where = f"continuation point {index}"
    if not isinstance(raw, Mapping):
        raise CalibrationError(f"{where}: not an object")
    for field in ("history_rows", "suffix", "route", "count", "samples_ns"):
        if field not in raw:
            raise CalibrationError(f"{where}: missing {field!r}")
    history = raw["history_rows"]
    suffix = raw["suffix"]
    if not _is_int(history) or not _is_int(suffix):
        raise CalibrationError(f"{where}: history_rows/suffix must be integers")
    if suffix <= 0 or history <= 0:
        raise CalibrationError(f"{where}: history_rows/suffix must be positive")
    route = raw["route"]
    if route not in ROUTES:
        raise CalibrationError(
            f"{where}: unknown route {route!r}; expected one of {list(ROUTES)}"
        )

    where = f"history {history} suffix {suffix} route {route}"
    samples = raw["samples_ns"]
    if not isinstance(samples, Sequence) or isinstance(samples, (str, bytes)):
        raise CalibrationError(f"{where}: 'samples_ns' is not a list")
    for sample in samples:
        if isinstance(sample, bool) or not isinstance(sample, (int, float)):
            raise CalibrationError(f"{where}: non-numeric sample {sample!r}")
        if sample <= 0:
            raise CalibrationError(f"{where}: non-positive sample {sample!r}")
    if raw["count"] != len(samples):
        raise CalibrationError(
            f"{where}: recorded count {raw['count']} but "
            f"{len(samples)} samples"
        )
    if len(samples) < MIN_WARM_SAMPLES:
        raise CalibrationError(
            f"{where}: {len(samples)} warm samples, Section 10.7 requires at "
            f"least {MIN_WARM_SAMPLES}"
        )

    p50 = percentile_ns(samples, 0.5)
    p95 = percentile_ns(samples, 0.95)
    for field, recomputed in (("p50_ns", p50), ("p95_ns", p95)):
        if field in raw and raw[field] != recomputed:
            raise CalibrationError(
                f"{where}: recorded {field} {raw[field]} does not match the "
                f"nearest-rank value {recomputed} recomputed from samples_ns"
            )
    return RoutePoint(history, suffix, route, len(samples), p50, p95)


def load_continuation_samples(document: Mapping) -> Measurements:
    """Validate a Task 13 baseline document and reduce it to p50/p95 points."""
    if not isinstance(document, Mapping):
        raise CalibrationError("baseline document is not an object")
    block = document.get("continuation")
    if not isinstance(block, Mapping):
        raise CalibrationError("baseline document has no 'continuation' object")

    interleaved = block.get("samples_interleaved")
    if interleaved is not True:
        raise CalibrationError(
            "this record is not marked samples_interleaved=true. Append and "
            "re-prefill measured in separate blocks cannot be compared on a "
            "machine whose throughput has been measured to swing 1.8x between "
            "runs; the first, non-interleaved crossover round was retracted "
            f"for exactly this. Got samples_interleaved={interleaved!r}."
        )

    declared_floor = block.get("warm_samples_per_point")
    if not _is_int(declared_floor) or declared_floor < MIN_WARM_SAMPLES:
        raise CalibrationError(
            f"warm_samples_per_point is {declared_floor!r}; Section 10.7 "
            f"requires at least {MIN_WARM_SAMPLES}"
        )

    raw_points = block.get("points")
    if not isinstance(raw_points, Sequence) or not raw_points:
        raise CalibrationError("'continuation.points' is missing or empty")

    points: dict = {}
    for index, raw in enumerate(raw_points):
        point = _require_point_fields(raw, index)
        bucket = points.setdefault((point.history_rows, point.suffix), {})
        if point.route in bucket:
            raise CalibrationError(
                f"duplicate point: history {point.history_rows} suffix "
                f"{point.suffix} route {point.route} appears more than once"
            )
        bucket[point.route] = point

    histories = sorted({key[0] for key in points})
    unexpected = [h for h in histories if h not in REQUIRED_HISTORIES]
    if unexpected:
        raise CalibrationError(
            f"unexpected history length(s) {unexpected}: Section 10.7's rule is "
            f"a conjunction over exactly {list(REQUIRED_HISTORIES)}, so an "
            f"extra history would change the rule rather than sharpen it"
        )
    missing = [h for h in REQUIRED_HISTORIES if h not in histories]
    if missing:
        raise CalibrationError(
            f"missing required history length(s) {missing}; Section 10.7 "
            f"requires {list(REQUIRED_HISTORIES)}"
        )

    suffixes = sorted({key[1] for key in points})
    missing = [s for s in REQUIRED_SUFFIXES if s not in suffixes]
    if missing:
        raise CalibrationError(
            f"missing required suffix length(s) {missing}; Section 10.7 "
            f"requires at least {list(REQUIRED_SUFFIXES)}"
        )

    for history in REQUIRED_HISTORIES:
        for suffix in suffixes:
            bucket = points.get((history, suffix), {})
            for route in ROUTES:
                if route not in bucket:
                    raise CalibrationError(
                        f"history {history} suffix {suffix}: no {route} point; "
                        f"both routes are needed to compare them"
                    )

    crossover = block.get("crossover")
    return Measurements(
        histories=tuple(sorted(REQUIRED_HISTORIES)),
        suffixes=tuple(suffixes),
        points=points,
        identity=document.get("identity") or {},
        recorded_crossover=crossover if isinstance(crossover, Mapping) else {},
        decision_rule=str(block.get("decision_rule") or ""),
    )


# --------------------------------------------------------------------------
# Cross-run agreement
# --------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class HistoryRow:
    utc: str
    interleaved: bool
    comparable: bool
    # `min` over that run's per-history winner ceilings. An UPPER BOUND on what
    # Section 10.7 would have selected from it, not the selection itself -- see
    # `history_agreement` for why the two differ.
    upper_bound: int
    permits: bool
    tight: bool
    note: str


@dataclasses.dataclass(frozen=True)
class HistoryReport:
    rows: tuple
    comparable: bool
    # Every interleaved run bounds the threshold at or above its value.
    permits: bool
    # The interleaved runs whose bound the threshold exactly meets.
    tight: tuple
    diagnostics: tuple


def history_agreement(records: Sequence[Mapping], threshold: int) -> HistoryReport:
    """Do the earlier runs PERMIT this constant? Not: would they select it.

    Each crossover record carries, per history, the bracket `[lower, upper]`.
    The lower edge is the largest suffix at which append decisively won, so it
    is that run's per-history winner CEILING. The minimum of those ceilings is
    an **upper bound** on what Section 10.7 would have selected from that run,
    and in general it is only an upper bound.

    The reason matters, because the obvious reading is wrong. Section 10.7
    selects the largest suffix in the INTERSECTION of the per-history winner
    sets, and `min` of the ceilings equals that only when each winner set is
    downward-closed. It need not be. Take sampled `{1, 2, 4, 8}` with
    `W512 = {1, 8}` and `W2048 = {1, 2, 4}`: the intersection is `{1}`, which
    is a prefix, so the monotonicity assertion passes and the rule returns 1 --
    while `min(8, 4)` is 4. A crossover record stores only the edges, never the
    winner sets, so downward-closure CANNOT be verified from it.

    What is sound without that assumption is the inequality: any suffix that
    wins at every history is at most every ceiling, hence at most their
    minimum. So this function checks

        threshold <= min(ceilings)                          -- sound, enforced
        threshold == min(ceilings)                          -- "tight", reported

    A run whose bound the threshold EXCEEDS contradicts it outright and is a
    hard diagnostic. A run whose bound it merely meets is consistent, and is
    reported as tight only under the stated assumption. A run whose bound it
    falls below permits the constant without confirming it.

    Task 13's finding is that the lower edges are stable and the upper edges
    are not; because this bound touches only the lower edges, an unstable upper
    edge cannot move it. Non-interleaved records are shown but excluded from
    the verdict.
    """
    if not _is_int(threshold) or threshold < 0:
        raise CalibrationError(f"threshold {threshold!r} is not a non-negative int")

    rows = []
    for index, record in enumerate(records):
        if not isinstance(record, Mapping):
            raise CalibrationError(f"crossover history record {index} is not an object")
        edges = record.get("edges")
        if not isinstance(edges, Mapping):
            raise CalibrationError(
                f"crossover history record {index} has no 'edges' object"
            )
        interleaved = record.get("samples_interleaved") is True
        lowers = []
        for history in REQUIRED_HISTORIES:
            pair = edges.get(str(history), edges.get(history))
            if not isinstance(pair, Sequence) or len(pair) != 2:
                raise CalibrationError(
                    f"crossover history record {index}: no [lower, upper] edge "
                    f"pair for history {history}"
                )
            lower = pair[0]
            if lower is None:
                lowers.append(0)
            elif _is_int(lower) and lower >= 0:
                lowers.append(lower)
            else:
                raise CalibrationError(
                    f"crossover history record {index}: history {history} lower "
                    f"edge {lower!r} is not a non-negative integer or null"
                )
        upper_bound = min(lowers)
        rows.append(
            HistoryRow(
                utc=str(record.get("utc", "")),
                interleaved=interleaved,
                comparable=interleaved,
                upper_bound=upper_bound,
                permits=interleaved and threshold <= upper_bound,
                tight=interleaved and threshold == upper_bound,
                note=str(record.get("note", "")),
            )
        )

    comparable_rows = [row for row in rows if row.comparable]
    diagnostics = []
    if not comparable_rows:
        diagnostics.append(
            "no interleaved run is on record, so nothing cross-checks this "
            "constant; a non-interleaved run cannot, because its two routes "
            "were not measured against the same machine state"
        )
    contradicting = [row for row in comparable_rows if not row.permits]
    if contradicting:
        diagnostics.append(
            "the constant exceeds what an interleaved run can support: "
            + ", ".join(
                f"{row.utc} bounds it at {row.upper_bound}" for row in contradicting
            )
            + f", and the selected threshold is {threshold}. At that run, some "
            "history had already stopped favouring append below this suffix "
            "length. A release-fixed constant that one recorded run "
            "contradicts is a decision for a human, not for this script."
        )
    return HistoryReport(
        rows=tuple(rows),
        comparable=bool(comparable_rows),
        permits=bool(comparable_rows) and not contradicting,
        tight=tuple(row for row in comparable_rows if row.tight),
        diagnostics=tuple(diagnostics),
    )


# --------------------------------------------------------------------------
# The generated header
# --------------------------------------------------------------------------


def apply_threshold_to_header(
    source: str,
    threshold: int,
    provenance: Sequence[str],
) -> str:
    """Replace the generated threshold block in an existing header.

    The whole file is NOT overwritten. `phi4_corelib_aie4_tuning.hpp` also
    holds `SelectContinuationRoute`, `ContinuationRoute` and
    `ForcedContinuationRoute`, all hand-written and all depended on by the
    frontend; regenerating the file wholesale would delete them. Only the
    declaration, and the marker block around it, are generated.
    """
    if not _is_int(threshold) or threshold < 0:
        raise CalibrationError(f"threshold {threshold!r} is not a non-negative int")

    lines = [_HEADER_BEGIN, "//"]
    # `f"// {line}"` on a blank provenance line would leave trailing
    # whitespace, which some editors and hooks strip -- and a stripped file
    # would then fail `--check` for a reason that has nothing to do with the
    # measurement.
    lines += [f"// {line}".rstrip() for line in provenance]
    lines.append(
        f"inline constexpr std::uint32_t kContinuationAppendThreshold "
        f"= {threshold};"
    )
    lines.append(_HEADER_END)
    block = "\n".join(lines)

    begin = source.find(_HEADER_BEGIN)
    end = source.find(_HEADER_END)
    if begin != -1 and end != -1:
        if source.count(_HEADER_BEGIN) != 1 or source.count(_HEADER_END) != 1:
            raise CalibrationError("header has more than one generated block")
        return source[:begin] + block + source[end + len(_HEADER_END) :]
    if begin != -1 or end != -1:
        raise CalibrationError("header has an unterminated generated block")

    matches = _HEADER_DECL.findall(source)
    if not matches:
        raise CalibrationError(
            "header has no 'inline constexpr std::uint32_t "
            "kContinuationAppendThreshold = <n>;' declaration to replace"
        )
    if len(matches) > 1:
        raise CalibrationError(
            f"header declares kContinuationAppendThreshold {len(matches)} times"
        )
    return _HEADER_DECL.sub(lambda _: block, source, count=1)


# --------------------------------------------------------------------------
# The published evidence
# --------------------------------------------------------------------------


def _ms(nanoseconds: float) -> str:
    return f"{nanoseconds / 1e6:,.1f} ms"


def conceded_points(measurements: Measurements, threshold: int) -> tuple:
    """What the single constant gives up, worst cost first.

    A conceded point is a `(history, suffix)` where append p95 beat re-prefill
    p95 but the suffix exceeds the threshold, so the route goes to re-prefill
    anyway. Ordered by SLOWDOWN, descending -- not by suffix.

    That ordering is the point. The penalty is `reprefill - append`; append
    grows with suffix length and re-prefill is roughly flat in it, so within a
    conceded band the NARROWEST suffix is the most expensive one. Quoting the
    widest conceded suffix understates the cost, which is the mistake this
    function exists to prevent.

    Returns `(history, suffix, penalty_ns, slowdown)` tuples.
    """
    winners = measurements.winners_by_history()
    points = []
    for history in measurements.histories:
        for suffix in winners[history]:
            if suffix <= threshold:
                continue
            append = measurements.point(history, suffix, "append").p95_ns
            reprefill = measurements.point(history, suffix, "reprefill").p95_ns
            points.append(
                (
                    history,
                    suffix,
                    reprefill - append,
                    reprefill / append if append else float("inf"),
                )
            )
    return tuple(sorted(points, key=lambda row: (-row[3], row[0], row[1])))


def _identity_rows(identity: Mapping) -> list:
    wanted = (
        ("machine", "machine"),
        ("CPU", "cpu_sku"),
        ("NPU", "npu_sku"),
        ("NPU driver", "npu_driver_version"),
        ("corelib SHA-256", "corelib_dll_sha256"),
        ("corelib source revision", "corelib_source_revision"),
        ("model SHA-256", "model_sha256"),
        ("FastFlow revision", "fastflow_revision"),
        ("measured (UTC)", "utc"),
    )
    return [
        (label, str(identity[key]))
        for label, key in wanted
        if identity.get(key) is not None
    ]


def build_document_section(
    measurements: Measurements,
    selection: Selection,
    agreement: HistoryReport,
) -> str:
    """Render the Section 15.6 telemetry for the selected constant."""
    winners = measurements.winners_by_history()
    unclosed = measurements.unclosed_histories()
    out = []
    add = out.append

    add(_DOCUMENT_BEGIN)
    add("")
    add("## Phi-4 continuation routing — the release-fixed threshold")
    add("")
    add(
        "Design Section 10.7 fixes ONE integer for the release and applies it "
        "at every history length: append when the suffix is at most the "
        "threshold, clear and re-prefill when it is larger. It is a FastFlow "
        "backend constant — not model-package data, not a runtime "
        "calibration — so route choice does not drift with thermal state or "
        "load."
    )
    add("")
    add(f"```cpp")
    add(f"inline constexpr std::uint32_t kContinuationAppendThreshold = "
        f"{selection.threshold};")
    add("```")
    add("")

    if selection.verdict == "selected":
        add(
            f"**Selected: {selection.threshold}.** Suffix lengths "
            f"{list(selection.winners)} are the sampled lengths whose append "
            f"p95 is lower than re-prefill p95 at BOTH measured history "
            f"lengths, and they form a prefix of the sampled set "
            f"{list(selection.ordered)}, so the largest of them is the "
            f"threshold."
        )
    else:
        add(
            f"**Selected: 0 — every prefix hit re-prefills.** "
            + " ".join(selection.diagnostics)
        )
    add("")

    add("### Which sampled lengths append wins, per history")
    add("")
    add("| history rows | append p95 wins at | last winning length |")
    add("| ---: | :--- | ---: |")
    for history in measurements.histories:
        won = winners[history]
        add(
            f"| {history} | {list(won) if won else 'none'} | "
            f"{max(won) if won else 0} |"
        )
    add("")
    add(
        f"The rule is a conjunction, so the constant is the smaller of those "
        f"ceilings. It is NOT a per-history policy: Section 10.7 specifies one "
        f"integer, and one integer cannot be optimal at two history lengths "
        f"whose crossovers differ."
    )
    add("")

    add("### What the single constant gives up")
    add("")
    concessions = conceded_points(measurements, selection.threshold)
    if concessions:
        # EVERY conceded point is listed, worst cost first. Naming a
        # representative one would understate the cost: the penalty is
        # `reprefill - append`, append grows with suffix length and re-prefill
        # does not, so the most expensive point in a conceded band is its
        # NARROWEST suffix, not its widest.
        worst = concessions[0]
        add(
            f"**Worst case: history {worst[0]}, suffix {worst[1]} — "
            f"{worst[3]:,.1f}x slower, +{_ms(worst[2])}.** Every conceded point "
            f"follows, ordered by slowdown. The widest conceded suffix is not "
            f"the most expensive one, because append cost grows with suffix "
            f"length while re-prefill cost does not — so the band's cost must "
            f"be read off its narrow end."
        )
        add("")
        add(
            "| history rows | suffix | append p95 | re-prefill p95 | route "
            "taken | penalty | slowdown |"
        )
        add("| ---: | ---: | ---: | ---: | :--- | ---: | ---: |")
        for history, suffix, penalty, slowdown in concessions:
            add(
                f"| {history} | {suffix} | "
                f"{_ms(measurements.point(history, suffix, 'append').p95_ns)} | "
                f"{_ms(measurements.point(history, suffix, 'reprefill').p95_ns)} "
                f"| re-prefill | +{_ms(penalty)} | {slowdown:,.1f}x |"
            )
        for history in measurements.histories:
            if not any(row[0] == history for row in concessions):
                add(f"| {history} | none | — | — | — | — | — |")
        add("")
        add(
            "Those are measured losses taken deliberately. The alternative — a "
            "threshold above the smaller ceiling — is optimal for the longer "
            "history and WRONG for the shorter one, where it would append past "
            "the point at which append has already lost. Conceding measured "
            "throughput at one history is the cheaper error than routing "
            "against the measurement at the other."
        )
        add("")
        add(
            "There is a second reason to prefer the smaller ceiling, and it is "
            "about confidence rather than cost. Task 13 measured this crossover "
            "three times and found the bracket's LOWER edge stable across runs "
            "and its UPPER edge not: the upper edge moves with how quiet the "
            "machine was, because that is what decides how many points near the "
            "crossover can be called at all. The threshold selected here sits "
            "at or below the lower edge at every measured history, so it is "
            "inside the append-wins region on every run. A threshold chosen "
            "from the upper edge would be supported by some runs and not "
            "others."
        )
    else:
        add(
            "Nothing. At every measured history length, append wins at no "
            "sampled suffix length beyond the threshold, so the single "
            "constant costs nothing that the measurement can see."
        )
    add("")

    add("### The measurement behind it")
    add("")
    add("| history rows | suffix | append p50 | append p95 | re-prefill p50 | "
        "re-prefill p95 | append p95 wins |")
    add("| ---: | ---: | ---: | ---: | ---: | ---: | :---: |")
    for history in measurements.histories:
        for suffix in measurements.suffixes:
            append = measurements.point(history, suffix, "append")
            reprefill = measurements.point(history, suffix, "reprefill")
            add(
                f"| {history} | {suffix} | {_ms(append.p50_ns)} | "
                f"{_ms(append.p95_ns)} | {_ms(reprefill.p50_ns)} | "
                f"{_ms(reprefill.p95_ns)} | "
                f"{'yes' if append.p95_ns < reprefill.p95_ns else 'no'} |"
            )
    add("")
    add(
        f"At least {MIN_WARM_SAMPLES} warm samples per route per point, "
        f"append and re-prefill interleaved WITHIN each point. p50 and p95 are "
        f"nearest-rank and were recomputed from the raw samples by the "
        f"calibrator, not copied."
    )
    add("")

    add("### Do the earlier runs permit this constant?")
    add("")
    add(
        "Not: would they have selected it. Each recorded crossover run carries, "
        "per history, the bracket `[lower, upper]`, and the lower edge is that "
        "run's per-history winner CEILING. The minimum of those ceilings is an "
        "**upper bound** on what Section 10.7 would have selected from that "
        "run, and in general only an upper bound: the rule takes the largest "
        "suffix in the INTERSECTION of the winner sets, which equals the "
        "minimum of the ceilings only when each winner set is downward-closed. "
        "A crossover record stores the edges and never the winner sets, so that "
        "property cannot be checked from it. What holds with no assumption is "
        "the inequality — any suffix winning at every history is at most every "
        "ceiling — so that is what is enforced here."
    )
    add("")
    add(
        "Task 13 measured the lower edges to be stable and the upper edges not. "
        "This bound touches only the lower edges, which is why an unstable "
        "upper edge cannot move it."
    )
    add("")
    add("| measured (UTC) | interleaved | bounds the threshold at | permits "
        f"{selection.threshold} | meets the bound exactly |")
    add("| --- | :---: | ---: | :---: | :---: |")
    for row in agreement.rows:
        if not row.comparable:
            add(
                f"| {row.utc} | no | ({row.upper_bound}) | excluded — routes "
                f"not measured against the same machine state | — |"
            )
        else:
            add(
                f"| {row.utc} | yes | {row.upper_bound} | "
                f"{'yes' if row.permits else 'NO'} | "
                f"{'yes' if row.tight else 'no'} |"
            )
    add("")
    if agreement.permits:
        tight = len(agreement.tight)
        total = sum(1 for row in agreement.rows if row.comparable)
        add(
            f"Every interleaved run on record permits {selection.threshold}, "
            f"and {tight} of {total} bound it there exactly. An exactly-met "
            f"bound is what "
            f"\"that run would have selected the same constant\" would need, "
            f"but only under the downward-closure assumption above, which its "
            f"record does not attest."
        )
    else:
        for line in agreement.diagnostics:
            add(f"**{line}**")
    add("")
    if unclosed:
        add(
            "**This run's own winner sets are not all downward-closed**, which "
            "is the condition under which the bound above stops being an "
            "equality — and, more importantly, means append lost at a short "
            "suffix and won again at a longer one:"
        )
        for line in unclosed:
            add(f"- {line}")
    else:
        add(
            "This run's own per-history winner sets ARE downward-closed at "
            "every history, checked directly from the sampled points rather "
            "than assumed. That is only a property of this run; it says nothing "
            "about the earlier ones, whose winner sets were never recorded."
        )
    add("")
    add(
        "The non-interleaved rows are shown for provenance and excluded from "
        "the verdict, because their two routes were measured in separate "
        "blocks and a machine regime shift there lands on one route and not "
        "the other. The first of them bounds the constant lower for a reason "
        "that has nothing to do with the machine: it swept only the five "
        "suffix lengths Section 10.7 names, and on `{1, 2, 32, 128, 256}` the "
        "last winning sampled length is 2 whether the true crossover is at 3 "
        "or at 31. **Two earlier answers are withdrawn and must not be "
        "reused: the threshold `2` from that sparse grid, and the "
        "extrapolated figures `≈9 at history 512, ≈26 at history 2048` from a "
        "contended non-interleaved run.**"
    )
    add("")
    add(
        "**The selection RULE is Section 10.7's, verbatim and unqualified; the "
        "measurement GRID is wider than Section 10.7 specifies, deliberately.** "
        "Those are two different things and only one of them changed. The rule "
        "— largest suffix whose append p95 is lower at both history lengths, "
        "after asserting the winners are prefix-contiguous — was applied as "
        "written. The grid was not: Section 10.7 names five suffix lengths, and "
        "on those five alone this same measurement yields 2, the answer since "
        "retracted as a grid artifact. Locating a crossover needs sample points "
        "near it, so the five named lengths are treated as a floor and every "
        "additional measured length is used. The measurement plan was "
        "corrected; the decision rule was not touched."
    )
    add("")

    add("### Identity of the run this constant came from")
    add("")
    add("| | |")
    add("| --- | --- |")
    for label, value in _identity_rows(measurements.identity):
        add(f"| {label} | `{value}` |")
    add("")
    add(
        "**\"Release-fixed\" does not mean hardware-independent.** Every "
        "measurement behind this constant comes from the single machine, "
        "corelib build and model named above. Nothing here establishes where "
        "the crossover sits on different silicon, on a corelib whose append or "
        "prefill path changed, or on a different model. Section 10.7 fixes the "
        "constant for the release rather than calibrating at run time, so that "
        "scope is intended — but a port to other hardware needs this "
        "re-measured, not inherited."
    )
    add("")
    add(
        "The timing table above is published here and is NOT shipped in the "
        "model package: Section 10.7 carries the threshold and no cost table."
    )
    add("")
    add(_DOCUMENT_END)
    return "\n".join(out) + "\n"


def apply_section_to_document(source: str, section: str) -> str:
    begin = source.find(_DOCUMENT_BEGIN)
    end = source.find(_DOCUMENT_END)
    if begin != -1 and end != -1:
        return source[:begin] + section.rstrip("\n") + source[end + len(_DOCUMENT_END) :]
    if begin != -1 or end != -1:
        raise CalibrationError("document has an unterminated threshold section")
    prefix = source if source.endswith("\n") else source + "\n"
    return prefix + "\n" + section


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------


def _read_json(path: pathlib.Path, what: str):
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as error:
        raise CalibrationError(f"cannot read {what} {path}: {error}") from error
    try:
        return json.loads(text)
    except json.JSONDecodeError as error:
        raise CalibrationError(f"{what} {path} is not valid JSON: {error}") from error


def _provenance(measurements: Measurements, selection: Selection) -> list:
    identity = measurements.identity
    concessions = conceded_points(measurements, selection.threshold)
    return [
        "Generated. Do not edit this block by hand; re-run the calibrator.",
        "",
        "Design Section 10.7: the largest sampled suffix length whose append",
        "p95 is lower than re-prefill p95 at BOTH history lengths "
        f"{list(measurements.histories)},",
        "after asserting the winning lengths are a prefix of the sampled set.",
        "",
        f"verdict:  {selection.verdict}",
        f"winners:  {list(selection.winners)} of sampled {list(selection.ordered)}",
        f"measured: {identity.get('utc', 'unknown')} on "
        f"{identity.get('machine', 'unknown')}",
        f"corelib:  {identity.get('corelib_dll_sha256', 'unknown')}",
        f"model:    {identity.get('model_sha256', 'unknown')}",
        "",
        "RELEASE-FIXED IS NOT HARDWARE-INDEPENDENT. Every measurement behind",
        "this value comes from the single machine, corelib build and model",
        "above. Nothing establishes where the crossover sits on different",
        "silicon, on a corelib whose append or prefill path changed, or on a",
        "different model. A port needs this re-measured, not inherited.",
        "",
        "What this value gives up, measured: "
        + (
            "; ".join(
                f"history {history} suffix {suffix} "
                f"({slowdown:,.1f}x slower, +{delta / 1e6:,.1f} ms)"
                for history, suffix, delta, slowdown in concessions
            )
            if concessions
            else "nothing the measurement can see"
        )
        + ".",
    ]


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Select the release-fixed Phi-4 continuation threshold.",
    )
    parser.add_argument("--baseline", required=True, type=pathlib.Path)
    parser.add_argument("--crossover-history", required=True, type=pathlib.Path)
    parser.add_argument("--header", required=True, type=pathlib.Path)
    parser.add_argument("--document", required=True, type=pathlib.Path)
    parser.add_argument("--json", type=pathlib.Path, default=None)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the checked-in header and document already match; write "
        "nothing and exit non-zero if they do not",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    try:
        measurements = load_continuation_samples(
            _read_json(args.baseline, "baseline")
        )
        selection = select_threshold_detailed(measurements.samples())
        crossover_notes = measurements.crossover_disagreements(selection)
        unclosed = measurements.unclosed_histories()
        records = _read_json(args.crossover_history, "crossover history")
        if not isinstance(records, Sequence) or isinstance(records, (str, bytes)):
            raise CalibrationError("crossover history is not a list of records")
        agreement = history_agreement(records, selection.threshold)

        section = build_document_section(measurements, selection, agreement)
        provenance = _provenance(measurements, selection)

        try:
            header_source = args.header.read_text(encoding="utf-8")
        except OSError as error:
            raise CalibrationError(
                f"cannot read header {args.header}: {error}"
            ) from error
        header_wanted = apply_threshold_to_header(
            header_source, selection.threshold, provenance
        )
        try:
            document_source = args.document.read_text(encoding="utf-8")
        except OSError as error:
            raise CalibrationError(
                f"cannot read document {args.document}: {error}"
            ) from error
        document_wanted = apply_section_to_document(document_source, section)
    except CalibrationError as error:
        print(f"calibration refused: {error}", file=sys.stderr)
        return 2

    for line in selection.diagnostics:
        print(f"diagnostic: {line}", file=sys.stderr)
    for line in crossover_notes:
        print(f"diagnostic: {line}", file=sys.stderr)
    for line in unclosed:
        print(f"diagnostic: {line}", file=sys.stderr)
    for line in agreement.diagnostics:
        print(f"diagnostic: {line}", file=sys.stderr)

    failed = []
    if crossover_notes:
        failed.append(
            "the Section 10.7 p95 rule contradicts the recorded bracket"
        )
    if unclosed:
        failed.append(
            "a per-history winner set is not downward-closed, so append lost "
            "at a short suffix and won again at a longer one"
        )
    if not agreement.permits:
        failed.append("the constant is contradicted by an interleaved run")

    stale = []
    if args.check:
        if header_source != header_wanted:
            stale.append(f"{args.header} is stale")
        if document_source != document_wanted:
            stale.append(f"{args.document} is stale")
        for line in stale:
            print(f"stale: {line}", file=sys.stderr)
    else:
        if not failed:
            args.header.write_text(header_wanted, encoding="utf-8", newline="\n")
            args.document.write_text(
                document_wanted, encoding="utf-8", newline="\n"
            )
        else:
            print(
                "refusing to write the header or the document; see the "
                "diagnostics above",
                file=sys.stderr,
            )

    if args.json is not None:
        args.json.write_text(
            json.dumps(
                {
                    "threshold": selection.threshold,
                    "verdict": selection.verdict,
                    "winners": list(selection.winners),
                    "sampled_suffixes": list(selection.ordered),
                    "winners_by_history": {
                        str(history): list(won)
                        for history, won in measurements.winners_by_history().items()
                    },
                    "diagnostics": list(selection.diagnostics)
                    + list(crossover_notes)
                    + list(unclosed)
                    + list(agreement.diagnostics),
                    "winners_downward_closed": not unclosed,
                    "history_agreement": {
                        "comparable": agreement.comparable,
                        "permits": agreement.permits,
                        "tight": [row.utc for row in agreement.tight],
                        "rows": [
                            dataclasses.asdict(row) for row in agreement.rows
                        ],
                    },
                    "identity": dict(measurements.identity),
                    "checked": bool(args.check),
                    "stale": stale,
                },
                indent=1,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
            newline="\n",
        )

    print(f"threshold = {selection.threshold} ({selection.verdict})")
    if failed or stale:
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
