"""Select the release-fixed Phi-4 continuation append threshold. Task 14.

Design Section 10.7 fixes ONE integer, `kContinuationAppendThreshold`, applied
regardless of history length:

    append when `suffix_tokens <= continuation_append_threshold`; and
    clear plus fresh re-prefill when the suffix is larger.

and it fixes how that integer is chosen:

    the largest suffix length whose append p95 is lower at both history
    lengths, but only after asserting that the set of winning sampled lengths
    is a prefix-contiguous set. If the winners are non-monotonic or none wins,
    the threshold is zero and every prefix hit re-prefills.

This script implements exactly that sentence against the committed Task 13
measurement. Three things about it are worth stating up front, because each is
a place where an obvious implementation would be wrong.

**The conjunction is over histories, and it is not a worst-case reduction.**
"Append p95 is lower at both history lengths" means `append[h] < reprefill[h]`
for every `h`. Collapsing the histories first -- comparing the largest append
p95 against the smallest re-prefill p95 -- is strictly stronger and would
reject suffixes that genuinely win at both.

**The suffix grid is a floor, not a whitelist.** Section 10.7 names suffix
lengths 1, 2, 32, 128 and 256. Task 13 measured that grid and reported the
threshold 2; that answer was retracted, because on `{1, 2, 32, ...}` the last
winning sampled length is 2 whether the true crossover is at 3 or at 31. The
denser 11-point grid Task 13 went on to measure resolves it. So the five named
lengths are REQUIRED to be present and every additional measured length is
USED. Dropping the extra points would faithfully reproduce a retracted answer.
The two history lengths are treated the other way round -- required and
exclusive -- because the conjunction ranges over them, so adding a third would
silently change the rule rather than sharpen it.

**A non-interleaved record is refused outright.** In a non-interleaved run the
two routes are measured in separate blocks, so a machine regime shift lands on
one route and not the other. On the shared lab box that is not hypothetical:
Task 13 measured a 1.8x swing in decode throughput between runs of the same
binary within two hours. The first round of the crossover sweep was
non-interleaved and its answer was retracted. Refusing is not the same as
selecting zero: zero is a measured outcome, and a record that cannot support
any outcome is an input error.

What this script does NOT do, deliberately: it does not emit a per-history
table, a cost model, or anything the runtime consults. Section 10.7 makes the
threshold a release-fixed backend constant, not model-package data and not a
runtime calibration, so the only artefact is one integer in a header.

Usage::

    python -m tools.calibrate_phi4_corelib_continuation \\
        --baseline docs/docs/benchmarks/phi4_aie4_baseline.json \\
        --crossover-history docs/docs/benchmarks/phi4_aie4_crossover_history.json \\
        --header src/include/models/phi4/phi4_corelib_aie4_tuning.hpp \\
        --document docs/docs/benchmarks/phi4_results.md [--check]
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import math
import pathlib
import re
import sys
from typing import Iterable, Mapping, Sequence

# Section 10.7 pins both history lengths. The winner rule is a conjunction over
# this set, so it is required AND exclusive: see the module docstring.
REQUIRED_HISTORIES = (512, 2048)

# Section 10.7 pins these suffix lengths as the measurement grid. They are a
# floor: any additional measured length is used. See the module docstring for
# why -- the five-point grid produced the retracted answer "2".
REQUIRED_SUFFIXES = (1, 2, 32, 128, 256)

MIN_WARM_SAMPLES = 5

ROUTES = ("append", "reprefill")

_HEADER_BEGIN = "// BEGIN generated by tools/calibrate_phi4_corelib_continuation.py"
_HEADER_END = "// END generated by tools/calibrate_phi4_corelib_continuation.py"
_HEADER_DECL = re.compile(
    r"^[ \t]*inline constexpr std::uint32_t kContinuationAppendThreshold"
    r"[ \t]*=[ \t]*\d+[ \t]*;[ \t]*$",
    re.MULTILINE,
)

_DOCUMENT_BEGIN = "<!-- BEGIN phi4-continuation-threshold -->"
_DOCUMENT_END = "<!-- END phi4-continuation-threshold -->"


class CalibrationError(Exception):
    """A record, header or document this script refuses to act on."""


# --------------------------------------------------------------------------
# Statistics
# --------------------------------------------------------------------------


def percentile_ns(samples: Iterable[float], quantile: float) -> float:
    """Nearest-rank percentile.

    Nearest-rank rather than an interpolating definition because that is what
    the Task 13 recorder used, and this script cross-checks every recorded
    p50/p95 against a recomputation from the raw samples. A different
    definition here would turn that cross-check into noise.
    """
    ordered = sorted(samples)
    if not ordered:
        raise CalibrationError("cannot take a percentile of zero samples")
    if not 0.0 < quantile <= 1.0:
        raise CalibrationError(f"quantile {quantile!r} is outside (0, 1]")
    rank = math.ceil(quantile * len(ordered))
    return ordered[min(len(ordered) - 1, max(0, rank - 1))]


# --------------------------------------------------------------------------
# The Section 10.7 selection rule
# --------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class Selection:
    threshold: int
    verdict: str
    winners: tuple
    ordered: tuple
    diagnostics: tuple


def _is_int(value) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def _number(entry: Mapping, key: str, where: str) -> float:
    if key not in entry:
        raise CalibrationError(f"{where}: missing {key!r}")
    value = entry[key]
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise CalibrationError(f"{where}: {key!r} is not a number: {value!r}")
    return float(value)


def _entry_wins(suffix, entry: Mapping) -> bool:
    """Does append beat re-prefill at EVERY history recorded for `suffix`?

    Two entry shapes are accepted and they must not be mixed:

      * `{"append_p95": x, "reprefill_p95": y}` -- one history; and
      * `{"per_history": {h: {"append_p95": x, "reprefill_p95": y}, ...}}`.

    The comparison is strict. Section 10.7 says append p95 must be LOWER, so a
    tie is not a win and routes to re-prefill.
    """
    where = f"suffix {suffix}"
    if not isinstance(entry, Mapping):
        raise CalibrationError(f"{where}: sample entry is not a mapping")
    flat = "append_p95" in entry or "reprefill_p95" in entry
    nested = "per_history" in entry
    if flat and nested:
        raise CalibrationError(
            f"{where}: entry mixes the flat and per-history shapes; pick one"
        )
    if not flat and not nested:
        raise CalibrationError(
            f"{where}: entry has neither 'append_p95'/'reprefill_p95' nor "
            f"'per_history'"
        )
    if flat:
        return _number(entry, "append_p95", where) < _number(
            entry, "reprefill_p95", where
        )

    per_history = entry["per_history"]
    if not isinstance(per_history, Mapping) or not per_history:
        raise CalibrationError(f"{where}: 'per_history' is empty")
    return all(
        _number(measured, "append_p95", f"{where} history {history}")
        < _number(measured, "reprefill_p95", f"{where} history {history}")
        for history, measured in sorted(per_history.items())
    )


def select_threshold_detailed(samples: Mapping) -> Selection:
    """Apply the Section 10.7 rule and say which branch it took.

    Verdicts: `empty`, `no_winner`, `non_monotonic`, `selected`. The first
    three all yield threshold zero -- every prefix hit re-prefills -- and only
    `non_monotonic` is a signal that something is wrong. With an unstable
    upper bracket edge, a non-prefix winner set says the machine moved during
    the sweep, not that append got faster at a longer suffix than a shorter
    one.
    """
    for suffix in samples:
        if not _is_int(suffix):
            raise CalibrationError(f"suffix length {suffix!r} is not an integer")
        if suffix <= 0:
            raise CalibrationError(f"suffix length {suffix!r} is not positive")

    ordered = tuple(sorted(samples))
    if not ordered:
        return Selection(
            0,
            "empty",
            (),
            (),
            ("no sampled suffix lengths; every prefix hit re-prefills",),
        )

    winners = tuple(suffix for suffix in ordered if _entry_wins(suffix, samples[suffix]))
    if not winners:
        return Selection(
            0,
            "no_winner",
            (),
            ordered,
            (
                "append p95 beat re-prefill p95 at no sampled suffix length; "
                "every prefix hit re-prefills",
            ),
        )

    prefix = ordered[: len(winners)]
    if winners != prefix:
        losses = [suffix for suffix in prefix if suffix not in winners]
        late = [suffix for suffix in winners if suffix not in prefix]
        return Selection(
            0,
            "non_monotonic",
            winners,
            ordered,
            (
                "the winning suffix lengths are not a prefix of the sampled "
                f"set: append lost at {losses} and then won again at {late}. "
                "Append cost grows with suffix length, so this is the machine "
                "moving during the sweep, not a real re-crossing. Threshold "
                "is zero and every prefix hit re-prefills.",
            ),
        )

    return Selection(int(max(winners)), "selected", winners, ordered, ())


def select_threshold(samples: Mapping) -> int:
    """The Section 10.7 rule, as one integer."""
    return select_threshold_detailed(samples).threshold


# --------------------------------------------------------------------------
# Ingestion
# --------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class RoutePoint:
    history_rows: int
    suffix: int
    route: str
    count: int
    p50_ns: float
    p95_ns: float


@dataclasses.dataclass(frozen=True)
class Measurements:
    histories: tuple
    suffixes: tuple
    points: Mapping
    identity: Mapping
    recorded_crossover: Mapping
    decision_rule: str

    def point(self, history: int, suffix: int, route: str) -> RoutePoint:
        return self.points[(history, suffix)][route]

    def samples(self) -> dict:
        """The `select_threshold` input, in the per-history shape."""
        return {
            suffix: {
                "per_history": {
                    history: {
                        "append_p95": self.point(history, suffix, "append").p95_ns,
                        "reprefill_p95": self.point(
                            history, suffix, "reprefill"
                        ).p95_ns,
                    }
                    for history in self.histories
                }
            }
            for suffix in self.suffixes
        }

    def winners_by_history(self) -> dict:
        """Per history, the suffix lengths at which append p95 wins."""
        return {
            history: tuple(
                suffix
                for suffix in self.suffixes
                if self.point(history, suffix, "append").p95_ns
                < self.point(history, suffix, "reprefill").p95_ns
            )
            for history in self.histories
        }

    def crossover_disagreements(self, selection: Selection) -> tuple:
        """Compare the p95 rule against the recorder's own p50-based verdict.

        Task 13's `append_wins_up_to` was decided by a different statistic -- a
        p50 gap that had to clear both the within-point spread and the drift
        across the point. Section 10.7's rule is p95. They should agree; where
        they do not, the constant rests on a statistic the published bracket
        contradicts, and that has to be said rather than resolved silently.
        """
        if not self.recorded_crossover:
            return ()
        found = []
        winners = self.winners_by_history()
        for history in self.histories:
            recorded = self.recorded_crossover.get(str(history))
            if not isinstance(recorded, Mapping):
                continue
            if "append_wins_up_to" not in recorded:
                continue
            declared = recorded["append_wins_up_to"]
            ours = max(winners[history]) if winners[history] else 0
            if declared is None:
                declared = 0
            if declared != ours:
                found.append(
                    f"history {history}: the recorded bracket says append wins "
                    f"up to {declared}, the Section 10.7 p95 rule says {ours}"
                )
        return tuple(found)


def _require_point_fields(raw, index: int) -> RoutePoint:
    where = f"continuation point {index}"
    if not isinstance(raw, Mapping):
        raise CalibrationError(f"{where}: not an object")
    for field in ("history_rows", "suffix", "route", "count", "samples_ns"):
        if field not in raw:
            raise CalibrationError(f"{where}: missing {field!r}")
    history = raw["history_rows"]
    suffix = raw["suffix"]
    if not _is_int(history) or not _is_int(suffix):
        raise CalibrationError(f"{where}: history_rows/suffix must be integers")
    if suffix <= 0 or history <= 0:
        raise CalibrationError(f"{where}: history_rows/suffix must be positive")
    route = raw["route"]
    if route not in ROUTES:
        raise CalibrationError(
            f"{where}: unknown route {route!r}; expected one of {list(ROUTES)}"
        )

    where = f"history {history} suffix {suffix} route {route}"
    samples = raw["samples_ns"]
    if not isinstance(samples, Sequence) or isinstance(samples, (str, bytes)):
        raise CalibrationError(f"{where}: 'samples_ns' is not a list")
    for sample in samples:
        if isinstance(sample, bool) or not isinstance(sample, (int, float)):
            raise CalibrationError(f"{where}: non-numeric sample {sample!r}")
        if sample <= 0:
            raise CalibrationError(f"{where}: non-positive sample {sample!r}")
    if raw["count"] != len(samples):
        raise CalibrationError(
            f"{where}: recorded count {raw['count']} but "
            f"{len(samples)} samples"
        )
    if len(samples) < MIN_WARM_SAMPLES:
        raise CalibrationError(
            f"{where}: {len(samples)} warm samples, Section 10.7 requires at "
            f"least {MIN_WARM_SAMPLES}"
        )

    p50 = percentile_ns(samples, 0.5)
    p95 = percentile_ns(samples, 0.95)
    for field, recomputed in (("p50_ns", p50), ("p95_ns", p95)):
        if field in raw and raw[field] != recomputed:
            raise CalibrationError(
                f"{where}: recorded {field} {raw[field]} does not match the "
                f"nearest-rank value {recomputed} recomputed from samples_ns"
            )
    return RoutePoint(history, suffix, route, len(samples), p50, p95)


def load_continuation_samples(document: Mapping) -> Measurements:
    """Validate a Task 13 baseline document and reduce it to p50/p95 points."""
    if not isinstance(document, Mapping):
        raise CalibrationError("baseline document is not an object")
    block = document.get("continuation")
    if not isinstance(block, Mapping):
        raise CalibrationError("baseline document has no 'continuation' object")

    interleaved = block.get("samples_interleaved")
    if interleaved is not True:
        raise CalibrationError(
            "this record is not marked samples_interleaved=true. Append and "
            "re-prefill measured in separate blocks cannot be compared on a "
            "machine whose throughput has been measured to swing 1.8x between "
            "runs; the first, non-interleaved crossover round was retracted "
            f"for exactly this. Got samples_interleaved={interleaved!r}."
        )

    declared_floor = block.get("warm_samples_per_point")
    if not _is_int(declared_floor) or declared_floor < MIN_WARM_SAMPLES:
        raise CalibrationError(
            f"warm_samples_per_point is {declared_floor!r}; Section 10.7 "
            f"requires at least {MIN_WARM_SAMPLES}"
        )

    raw_points = block.get("points")
    if not isinstance(raw_points, Sequence) or not raw_points:
        raise CalibrationError("'continuation.points' is missing or empty")

    points: dict = {}
    for index, raw in enumerate(raw_points):
        point = _require_point_fields(raw, index)
        bucket = points.setdefault((point.history_rows, point.suffix), {})
        if point.route in bucket:
            raise CalibrationError(
                f"duplicate point: history {point.history_rows} suffix "
                f"{point.suffix} route {point.route} appears more than once"
            )
        bucket[point.route] = point

    histories = sorted({key[0] for key in points})
    unexpected = [h for h in histories if h not in REQUIRED_HISTORIES]
    if unexpected:
        raise CalibrationError(
            f"unexpected history length(s) {unexpected}: Section 10.7's rule is "
            f"a conjunction over exactly {list(REQUIRED_HISTORIES)}, so an "
            f"extra history would change the rule rather than sharpen it"
        )
    missing = [h for h in REQUIRED_HISTORIES if h not in histories]
    if missing:
        raise CalibrationError(
            f"missing required history length(s) {missing}; Section 10.7 "
            f"requires {list(REQUIRED_HISTORIES)}"
        )

    suffixes = sorted({key[1] for key in points})
    missing = [s for s in REQUIRED_SUFFIXES if s not in suffixes]
    if missing:
        raise CalibrationError(
            f"missing required suffix length(s) {missing}; Section 10.7 "
            f"requires at least {list(REQUIRED_SUFFIXES)}"
        )

    for history in REQUIRED_HISTORIES:
        for suffix in suffixes:
            bucket = points.get((history, suffix), {})
            for route in ROUTES:
                if route not in bucket:
                    raise CalibrationError(
                        f"history {history} suffix {suffix}: no {route} point; "
                        f"both routes are needed to compare them"
                    )

    crossover = block.get("crossover")
    return Measurements(
        histories=tuple(sorted(REQUIRED_HISTORIES)),
        suffixes=tuple(suffixes),
        points=points,
        identity=document.get("identity") or {},
        recorded_crossover=crossover if isinstance(crossover, Mapping) else {},
        decision_rule=str(block.get("decision_rule") or ""),
    )


# --------------------------------------------------------------------------
# Cross-run agreement
# --------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class HistoryRow:
    utc: str
    interleaved: bool
    comparable: bool
    derived: int
    agrees: bool
    note: str


@dataclasses.dataclass(frozen=True)
class HistoryReport:
    rows: tuple
    comparable: bool
    agrees: bool
    diagnostics: tuple


def history_agreement(records: Sequence[Mapping], threshold: int) -> HistoryReport:
    """Would each earlier run have selected the same constant?

    Each crossover record carries, per history, the bracket `[lower, upper]`.
    The lower edge is the largest suffix at which append DECISIVELY won, so it
    is exactly that run's per-history winner ceiling, and the Section 10.7
    conjunction over histories is the minimum of those ceilings. That makes the
    constant recomputable from every recorded run without re-running anything.

    Task 13's finding is that the lower edges are stable and the upper edges
    are not; because this derivation touches only the lower edges, an
    unstable upper edge does not move the answer. Non-interleaved records are
    shown but excluded from the verdict.
    """
    if not _is_int(threshold) or threshold < 0:
        raise CalibrationError(f"threshold {threshold!r} is not a non-negative int")

    rows = []
    for index, record in enumerate(records):
        if not isinstance(record, Mapping):
            raise CalibrationError(f"crossover history record {index} is not an object")
        edges = record.get("edges")
        if not isinstance(edges, Mapping):
            raise CalibrationError(
                f"crossover history record {index} has no 'edges' object"
            )
        interleaved = record.get("samples_interleaved") is True
        lowers = []
        for history in REQUIRED_HISTORIES:
            pair = edges.get(str(history), edges.get(history))
            if not isinstance(pair, Sequence) or len(pair) != 2:
                raise CalibrationError(
                    f"crossover history record {index}: no [lower, upper] edge "
                    f"pair for history {history}"
                )
            lower = pair[0]
            if lower is None:
                lowers.append(0)
            elif _is_int(lower) and lower >= 0:
                lowers.append(lower)
            else:
                raise CalibrationError(
                    f"crossover history record {index}: history {history} lower "
                    f"edge {lower!r} is not a non-negative integer or null"
                )
        derived = min(lowers)
        rows.append(
            HistoryRow(
                utc=str(record.get("utc", "")),
                interleaved=interleaved,
                comparable=interleaved,
                derived=derived,
                agrees=interleaved and derived == threshold,
                note=str(record.get("note", "")),
            )
        )

    comparable_rows = [row for row in rows if row.comparable]
    diagnostics = []
    if not comparable_rows:
        diagnostics.append(
            "no interleaved run is on record, so nothing cross-checks this "
            "constant; a non-interleaved run cannot, because its two routes "
            "were not measured against the same machine state"
        )
    disagreeing = [row for row in comparable_rows if not row.agrees]
    if disagreeing:
        diagnostics.append(
            "the constant is not run-stable: interleaved run(s) "
            + ", ".join(f"{row.utc} would select {row.derived}" for row in disagreeing)
            + f", not {threshold}. A release-fixed constant that changes with "
            "the run is the wrong shape for this measurement; a human has to "
            "decide, not this script."
        )
    return HistoryReport(
        rows=tuple(rows),
        comparable=bool(comparable_rows),
        agrees=bool(comparable_rows) and not disagreeing,
        diagnostics=tuple(diagnostics),
    )


# --------------------------------------------------------------------------
# The generated header
# --------------------------------------------------------------------------


def apply_threshold_to_header(
    source: str,
    threshold: int,
    provenance: Sequence[str],
) -> str:
    """Replace the generated threshold block in an existing header.

    The whole file is NOT overwritten. `phi4_corelib_aie4_tuning.hpp` also
    holds `SelectContinuationRoute`, `ContinuationRoute` and
    `ForcedContinuationRoute`, all hand-written and all depended on by the
    frontend; regenerating the file wholesale would delete them. Only the
    declaration, and the marker block around it, are generated.
    """
    if not _is_int(threshold) or threshold < 0:
        raise CalibrationError(f"threshold {threshold!r} is not a non-negative int")

    lines = [_HEADER_BEGIN, "//"]
    # `f"// {line}"` on a blank provenance line would leave trailing
    # whitespace, which some editors and hooks strip -- and a stripped file
    # would then fail `--check` for a reason that has nothing to do with the
    # measurement.
    lines += [f"// {line}".rstrip() for line in provenance]
    lines.append(
        f"inline constexpr std::uint32_t kContinuationAppendThreshold "
        f"= {threshold};"
    )
    lines.append(_HEADER_END)
    block = "\n".join(lines)

    begin = source.find(_HEADER_BEGIN)
    end = source.find(_HEADER_END)
    if begin != -1 and end != -1:
        if source.count(_HEADER_BEGIN) != 1 or source.count(_HEADER_END) != 1:
            raise CalibrationError("header has more than one generated block")
        return source[:begin] + block + source[end + len(_HEADER_END) :]
    if begin != -1 or end != -1:
        raise CalibrationError("header has an unterminated generated block")

    matches = _HEADER_DECL.findall(source)
    if not matches:
        raise CalibrationError(
            "header has no 'inline constexpr std::uint32_t "
            "kContinuationAppendThreshold = <n>;' declaration to replace"
        )
    if len(matches) > 1:
        raise CalibrationError(
            f"header declares kContinuationAppendThreshold {len(matches)} times"
        )
    return _HEADER_DECL.sub(lambda _: block, source, count=1)


# --------------------------------------------------------------------------
# The published evidence
# --------------------------------------------------------------------------


def _ms(nanoseconds: float) -> str:
    return f"{nanoseconds / 1e6:,.1f} ms"


def _identity_rows(identity: Mapping) -> list:
    wanted = (
        ("machine", "machine"),
        ("CPU", "cpu_sku"),
        ("NPU", "npu_sku"),
        ("NPU driver", "npu_driver_version"),
        ("corelib SHA-256", "corelib_dll_sha256"),
        ("corelib source revision", "corelib_source_revision"),
        ("model SHA-256", "model_sha256"),
        ("FastFlow revision", "fastflow_revision"),
        ("measured (UTC)", "utc"),
    )
    return [
        (label, str(identity[key]))
        for label, key in wanted
        if identity.get(key) is not None
    ]


def build_document_section(
    measurements: Measurements,
    selection: Selection,
    agreement: HistoryReport,
) -> str:
    """Render the Section 15.6 telemetry for the selected constant."""
    winners = measurements.winners_by_history()
    out = []
    add = out.append

    add(_DOCUMENT_BEGIN)
    add("")
    add("## Phi-4 continuation routing — the release-fixed threshold")
    add("")
    add(
        "Design Section 10.7 fixes ONE integer for the release and applies it "
        "at every history length: append when the suffix is at most the "
        "threshold, clear and re-prefill when it is larger. It is a FastFlow "
        "backend constant — not model-package data, not a runtime "
        "calibration — so route choice does not drift with thermal state or "
        "load."
    )
    add("")
    add(f"```cpp")
    add(f"inline constexpr std::uint32_t kContinuationAppendThreshold = "
        f"{selection.threshold};")
    add("```")
    add("")

    if selection.verdict == "selected":
        add(
            f"**Selected: {selection.threshold}.** Suffix lengths "
            f"{list(selection.winners)} are the sampled lengths whose append "
            f"p95 is lower than re-prefill p95 at BOTH measured history "
            f"lengths, and they form a prefix of the sampled set "
            f"{list(selection.ordered)}, so the largest of them is the "
            f"threshold."
        )
    else:
        add(
            f"**Selected: 0 — every prefix hit re-prefills.** "
            + " ".join(selection.diagnostics)
        )
    add("")

    add("### Which sampled lengths append wins, per history")
    add("")
    add("| history rows | append p95 wins at | last winning length |")
    add("| ---: | :--- | ---: |")
    for history in measurements.histories:
        won = winners[history]
        add(
            f"| {history} | {list(won) if won else 'none'} | "
            f"{max(won) if won else 0} |"
        )
    add("")
    add(
        f"The rule is a conjunction, so the constant is the smaller of those "
        f"ceilings. It is NOT a per-history policy: Section 10.7 specifies one "
        f"integer, and one integer cannot be optimal at two history lengths "
        f"whose crossovers differ."
    )
    add("")

    add("### What the single constant gives up")
    add("")
    conceded = {
        history: [s for s in winners[history] if s > selection.threshold]
        for history in measurements.histories
    }
    if any(conceded.values()):
        add(
            "| history rows | suffixes append would have won and now loses | "
            "widest such suffix | append p95 there | re-prefill p95 there | "
            "route taken |"
        )
        add("| ---: | :--- | ---: | ---: | ---: | :--- |")
        for history in measurements.histories:
            given_up = conceded[history]
            if not given_up:
                add(f"| {history} | none | — | — | — | — |")
                continue
            worst = max(given_up)
            add(
                f"| {history} | {given_up} | {worst} | "
                f"{_ms(measurements.point(history, worst, 'append').p95_ns)} | "
                f"{_ms(measurements.point(history, worst, 'reprefill').p95_ns)} | "
                f"re-prefill |"
            )
        add("")
        add(
            "Those are measured losses taken deliberately. The alternative — a "
            "threshold above the smaller ceiling — is optimal for the longer "
            "history and WRONG for the shorter one, where it would append past "
            "the point at which append has already lost. Conceding measured "
            "throughput at one history is the cheaper error than routing "
            "against the measurement at the other."
        )
        add("")
        add(
            "There is a second reason to prefer the smaller ceiling, and it is "
            "about confidence rather than cost. Task 13 measured this crossover "
            "three times and found the bracket's LOWER edge stable across runs "
            "and its UPPER edge not: the upper edge moves with how quiet the "
            "machine was, because that is what decides how many points near the "
            "crossover can be called at all. The threshold selected here sits "
            "at or below the lower edge at every measured history, so it is "
            "inside the append-wins region on every run. A threshold chosen "
            "from the upper edge would be supported by some runs and not "
            "others."
        )
    else:
        add(
            "Nothing. At every measured history length, append wins at no "
            "sampled suffix length beyond the threshold, so the single "
            "constant costs nothing that the measurement can see."
        )
    add("")

    add("### The measurement behind it")
    add("")
    add("| history rows | suffix | append p50 | append p95 | re-prefill p50 | "
        "re-prefill p95 | append p95 wins |")
    add("| ---: | ---: | ---: | ---: | ---: | ---: | :---: |")
    for history in measurements.histories:
        for suffix in measurements.suffixes:
            append = measurements.point(history, suffix, "append")
            reprefill = measurements.point(history, suffix, "reprefill")
            add(
                f"| {history} | {suffix} | {_ms(append.p50_ns)} | "
                f"{_ms(append.p95_ns)} | {_ms(reprefill.p50_ns)} | "
                f"{_ms(reprefill.p95_ns)} | "
                f"{'yes' if append.p95_ns < reprefill.p95_ns else 'no'} |"
            )
    add("")
    add(
        f"At least {MIN_WARM_SAMPLES} warm samples per route per point, "
        f"append and re-prefill interleaved WITHIN each point. p50 and p95 are "
        f"nearest-rank and were recomputed from the raw samples by the "
        f"calibrator, not copied."
    )
    add("")

    add("### Would earlier runs have chosen the same constant?")
    add("")
    add(
        "Each recorded crossover run carries, per history, the bracket "
        "`[lower, upper]`. The lower edge IS that run's per-history winner "
        "ceiling, so the constant is recomputable from every recorded run. "
        "Task 13 measured the lower edges to be stable and the upper edges not; "
        "this derivation touches only the lower edges, which is why an unstable "
        "upper edge does not move the answer."
    )
    add("")
    add("| measured (UTC) | interleaved | would select | agrees with "
        f"{selection.threshold} |")
    add("| --- | :---: | ---: | :---: |")
    for row in agreement.rows:
        if not row.comparable:
            add(
                f"| {row.utc} | no | ({row.derived}) | excluded — routes not "
                f"measured against the same machine state |"
            )
        else:
            add(
                f"| {row.utc} | yes | {row.derived} | "
                f"{'yes' if row.agrees else 'NO'} |"
            )
    add("")
    if agreement.agrees:
        add(
            f"Every interleaved run on record would have selected "
            f"{selection.threshold}."
        )
    else:
        for line in agreement.diagnostics:
            add(f"**{line}**")
    add("")
    add(
        "The non-interleaved rows are shown for provenance and excluded from "
        "the verdict, because their two routes were measured in separate "
        "blocks and a machine regime shift there lands on one route and not "
        "the other. The first of them derives a smaller constant for a reason "
        "that has nothing to do with the machine: it swept only the five "
        "suffix lengths Section 10.7 names, and on `{1, 2, 32, 128, 256}` the "
        "last winning sampled length is 2 whether the true crossover is at 3 "
        "or at 31. **Two earlier answers are withdrawn and must not be "
        "reused: the threshold `2` from that sparse grid, and the "
        "extrapolated figures `≈9 at history 512, ≈26 at history 2048` from a "
        "contended non-interleaved run.** The calibrator therefore treats the "
        "five named lengths as a floor and uses every additional measured "
        "length."
    )
    add("")

    add("### Identity of the run this constant came from")
    add("")
    add("| | |")
    add("| --- | --- |")
    for label, value in _identity_rows(measurements.identity):
        add(f"| {label} | `{value}` |")
    add("")
    add(
        "The timing table above is published here and is NOT shipped in the "
        "model package: Section 10.7 carries the threshold and no cost table."
    )
    add("")
    add(_DOCUMENT_END)
    return "\n".join(out) + "\n"


def apply_section_to_document(source: str, section: str) -> str:
    begin = source.find(_DOCUMENT_BEGIN)
    end = source.find(_DOCUMENT_END)
    if begin != -1 and end != -1:
        return source[:begin] + section.rstrip("\n") + source[end + len(_DOCUMENT_END) :]
    if begin != -1 or end != -1:
        raise CalibrationError("document has an unterminated threshold section")
    prefix = source if source.endswith("\n") else source + "\n"
    return prefix + "\n" + section


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------


def _read_json(path: pathlib.Path, what: str):
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as error:
        raise CalibrationError(f"cannot read {what} {path}: {error}") from error
    try:
        return json.loads(text)
    except json.JSONDecodeError as error:
        raise CalibrationError(f"{what} {path} is not valid JSON: {error}") from error


def _provenance(measurements: Measurements, selection: Selection) -> list:
    identity = measurements.identity
    return [
        "Generated. Do not edit this block by hand; re-run the calibrator.",
        "",
        "Design Section 10.7: the largest sampled suffix length whose append",
        "p95 is lower than re-prefill p95 at BOTH history lengths "
        f"{list(measurements.histories)},",
        "after asserting the winning lengths are a prefix of the sampled set.",
        "",
        f"verdict:  {selection.verdict}",
        f"winners:  {list(selection.winners)} of sampled {list(selection.ordered)}",
        f"measured: {identity.get('utc', 'unknown')} on "
        f"{identity.get('machine', 'unknown')}",
        f"corelib:  {identity.get('corelib_dll_sha256', 'unknown')}",
        f"model:    {identity.get('model_sha256', 'unknown')}",
    ]


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Select the release-fixed Phi-4 continuation threshold.",
    )
    parser.add_argument("--baseline", required=True, type=pathlib.Path)
    parser.add_argument("--crossover-history", required=True, type=pathlib.Path)
    parser.add_argument("--header", required=True, type=pathlib.Path)
    parser.add_argument("--document", required=True, type=pathlib.Path)
    parser.add_argument("--json", type=pathlib.Path, default=None)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the checked-in header and document already match; write "
        "nothing and exit non-zero if they do not",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    try:
        measurements = load_continuation_samples(
            _read_json(args.baseline, "baseline")
        )
        selection = select_threshold_detailed(measurements.samples())
        crossover_notes = measurements.crossover_disagreements(selection)
        records = _read_json(args.crossover_history, "crossover history")
        if not isinstance(records, Sequence) or isinstance(records, (str, bytes)):
            raise CalibrationError("crossover history is not a list of records")
        agreement = history_agreement(records, selection.threshold)

        section = build_document_section(measurements, selection, agreement)
        provenance = _provenance(measurements, selection)

        try:
            header_source = args.header.read_text(encoding="utf-8")
        except OSError as error:
            raise CalibrationError(
                f"cannot read header {args.header}: {error}"
            ) from error
        header_wanted = apply_threshold_to_header(
            header_source, selection.threshold, provenance
        )
        try:
            document_source = args.document.read_text(encoding="utf-8")
        except OSError as error:
            raise CalibrationError(
                f"cannot read document {args.document}: {error}"
            ) from error
        document_wanted = apply_section_to_document(document_source, section)
    except CalibrationError as error:
        print(f"calibration refused: {error}", file=sys.stderr)
        return 2

    for line in selection.diagnostics:
        print(f"diagnostic: {line}", file=sys.stderr)
    for line in crossover_notes:
        print(f"diagnostic: {line}", file=sys.stderr)
    for line in agreement.diagnostics:
        print(f"diagnostic: {line}", file=sys.stderr)

    failed = []
    if crossover_notes:
        failed.append(
            "the Section 10.7 p95 rule contradicts the recorded bracket"
        )
    if not agreement.agrees:
        failed.append("the constant is not supported by every interleaved run")

    stale = []
    if args.check:
        if header_source != header_wanted:
            stale.append(f"{args.header} is stale")
        if document_source != document_wanted:
            stale.append(f"{args.document} is stale")
        for line in stale:
            print(f"stale: {line}", file=sys.stderr)
    else:
        if not failed:
            args.header.write_text(header_wanted, encoding="utf-8", newline="\n")
            args.document.write_text(
                document_wanted, encoding="utf-8", newline="\n"
            )
        else:
            print(
                "refusing to write the header or the document; see the "
                "diagnostics above",
                file=sys.stderr,
            )

    if args.json is not None:
        args.json.write_text(
            json.dumps(
                {
                    "threshold": selection.threshold,
                    "verdict": selection.verdict,
                    "winners": list(selection.winners),
                    "sampled_suffixes": list(selection.ordered),
                    "winners_by_history": {
                        str(history): list(won)
                        for history, won in measurements.winners_by_history().items()
                    },
                    "diagnostics": list(selection.diagnostics)
                    + list(crossover_notes)
                    + list(agreement.diagnostics),
                    "history_agreement": {
                        "comparable": agreement.comparable,
                        "agrees": agreement.agrees,
                        "rows": [
                            dataclasses.asdict(row) for row in agreement.rows
                        ],
                    },
                    "identity": dict(measurements.identity),
                    "checked": bool(args.check),
                    "stale": stale,
                },
                indent=1,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
            newline="\n",
        )

    print(f"threshold = {selection.threshold} ({selection.verdict})")
    if failed or stale:
        return 1
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
