title: FastFlowLM Documentation
description: Documentation for the FastFlowLM project
theme: just-the-docs

url: "https://FastFlowLM.github.io"
baseurl: "/FastFlowLM/docs"

# (Optional) Navigation structure
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Guides:
      - Advanced: guides/advanced.md
