title: FastFlowLM Docs
description: Documentation for the AMD-NPU-first LLM runtime
remote_theme: just-the-docs/just-the-docs

color_scheme: dark
search_enabled: true
nav_sort: case_insensitive

aux_links:
  GitHub Repo: https://github.com/FastFlowLM/FastFlowLM
