title: FastFlowLM Documentation
description: Documentation for the FastFlowLM project
theme: just-the-docs

url: "https://fastflowlm.github.io"
baseurl: "/FastFlowLM"

plugins:
  - just-the-docs

# Navigation structure (optional — only needed if you want to override automatic nav)
nav:
  - Home: index.md
